name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Lint:
    # Lint任务
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        # - uses: pnpm/action-setup@v2.1.0
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.x.x
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install modules
        run: pnpm install
      - name: Run Lint
        run: pnpm run lint
  UnitTest:
    # 单元测试任务
    # The types of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed  as part of the job
    steps:
      - uses: actions/checkout@v3
      # - uses: pnpm/action-setup@v2.1.0
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.x.x
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install modules
        run: pnpm install
      - name: Run Test
        run: pnpm run test:run
