name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Lint:
     # Lint任务
     # The type of runner that the job will run on 
     runs-on: ubuntu-latest
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       - uses: actions/checkout@v2
       - uses: pnpm/action-setup@v2.1.0
         with:
           node-version: 16.x.x
       - name: Install modules
         run: pnpm install
       - name: Run Lint
         run: pnpm run lint
  UnitTest:
     # 单元测试任务
     # The types of runner that the job will run on
     runs-on: ubuntu-latest
     # Steps represent a sequence of tasks that will be executed  as part of the job
     steps:
       - uses: actions/checkout@v2
       - uses: pnpm/action-setup@v2.1.0
         with:
           node-version: 16.x.x
       - name: Install modules
         run: pnpm install
       - name: Run Test
         run: pnpm run test:run
